sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 888Taotao@
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: sky-take-out-second-2026
  redis:
    host: localhost
    port: 6379
    password: 888Taotao@
    database: 10
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
  baidu:
    map:
      ak: ${BAIDU_MAP_AK}
      address: 温州市鹿城区嘉鸿花园12幢1606
      urls:
        geocoding: https://api.map.baidu.com/geocoding/v3/?
        riding: https://api.map.baidu.com/directionlite/v1/riding?